config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :follows, only: [:index ,:create, :destroy], shallow: true
    resources :followeds, only: [:index ,:create, :destroy], shallow: true
    resources :rooms do
      resources :room_messages, only: [:index, :create, :destroy], shallow: true
      collection do
        get "download", as: "download"
      end
    end
  end

  resources :posts, only: [:index, :create, :show, :edit, :update,:destroy] do
    resources :photos, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :posts, -> {order(:created_at => :desc)} , dependent: :destroy
  has_many :likes, -> {order(:created_at => :desc)}, dependent: :destroy
  has_many :comments, -> {order(:created_at => :desc)}, dependent: :destroy
  has_many :bookmarks, -> {order(:created_at => :desc)}, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :followeds, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :room_messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  gravtastic :email
  validates :name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.search(term)
    if term
      where('name LIKE ?', term + '%')
    else
      nil
    end
  end

  def is_followed
    Followed.find_by(user_id: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @search = User.search(params[:term])
    @user = User.find(params[:user_id])
    @room = Room.find(params[:room_id])
    respond_to :js
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @saved = Post.joins(:bookmarks).where("bookmarks.user_id = ?", current_user.id)
    @follow = Follow.joins("INNER JOIN followeds ON follows.id = followeds.follow_id").where(user_id: current_user.id)[0]
    @follows = User.joins(:follows).where(id: @user.id)
    @followeds = User.joins(:followeds).where(id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(name: params[:user][:name], email: params[:user][:email], avatar: params[:user][:avatar])
      flash[:notice] = "Success"
    else
      flash[:alert] = "Failed"
    end
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    if @user
      if @user.destroy
        flash[:notice] = "Byeeee"
      else
      flash[:alert] = "Something went wrong"
      end
    else
      flash[:alert] = "User does not existed"
    redirect_to root_path
    end
  end
end

app/views/users/_follow_button.html.erb
<% if user.is_followed %>
  <%= link_to "Followed", follow_path(follow.id), method: :delete, class: "btn common-btn followed-user-btn", remote: true %>
<% else %>
  <%= link_to "Follow", user_follows_path(user.id), method: :post, class: "btn common-btn follow-user-btn", remote: true %>
<% end %>

app/views/users/_post.html.erb
<% posts.each do |post| %>
  <div class="col-4">
    <%= link_to post_path(post) do %>
      <div class="post-stat d-flex justify-content-center align-items-center">
        <span>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <%= post.likes.size %>
          <i class="ml-3 fa fa-comment" aria-hidden="true"></i>
          <%= post.comments.size %>
        </span>
      </div>
      <%= image_tag post.photos.first.image, class: "card-img-top image-preview" %>
    <% end %>
  </div>
<% end %>

app/views/users/_user_result.html.erb
<% if users.present? %>
  <% users.each do |user| %>
    <%= link_to user_path(user), class: "no-text-decoration normal-color" do %>
      <div class="search-result-item"><%= user.name %></div>
    <% end %>
  <% end %>
<% else %>
  <div class="p-3">
    No results found
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="conatiner p-1 m-4 w-75 align-self-lg-center">
    <div class="row mx-lg-5 flex-column align-items-center">
        <%= form_for @user, url: user_path(@user), method: :patch, class: "md-form mt-5" do |f| %>
          <div class="col col-6">
            <%= image_tag user_avatar(@user), width: '125', height: '125', class: "round-img" %>
            <%= f.file_field :avatar, class:"m-3" %>
          </div>
          <div class="col col-6">
            <%= f.text_field :name, autocomplete: @user.name, class:"form-control border-0 text-left m-3" %>
            <%= f.text_field :email, autocomplete: @user.email, class:"form-control border-0 text-left m-3" %>
            <%= f.submit "Update", class:"btn btn-sm m-3 btn-outline-dark" %>
          </div>
        <% end %>
    </div>
</div>

app/views/users/index.js.erb
$(`#users-result`).html('<%= j render "user_result", {users: @search} %>');

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag user_avatar(@user), width: '160', height: '160', class: "round-img" %>
  </div>
  <%# byebug %>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-2 text-center">
        <div>
          <h3><%= @posts.count %></h3>
          <p class="btn">Posts</p>
        </div>
      </div>
      <div class="col-md-3 text-center">
        <div>
          <h3><%= @followeds.count %></h3>
          <%= link_to "Followers", user_followeds_path(@user), remote: true, method: :get, class: "btn" %>
        </div>
      </div>
      <div class="col-md-2 text-center">
        <div>
          <h3><%= @follows.count %></h3>
          <%= link_to "Following", user_follows_path(@user), remote: true, method: :get , class: "btn"%>
        </div>
      </div>
    </div>
    <div class="row">
      <p class="username"><%= @user.name %></p>
      <% if @user != current_user %>
        <div id = "follow-user-<%= @user.id %>" style="display: flex">
          <%= render "follow_button", {user: @user, follow: @follow} %>
        </div>
      <% else %>
        <%= link_to "Edit Profile", edit_user_path(current_user), method: :get, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"></button>
      <% end %>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <%= link_to "Change Password", edit_user_registration_path, method: :get, class:"list-group-item list-group-item-action" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete,
                class: "list-group-item list-group-item-action" %>
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <p class="email"><%= @user.email %></p>
    </div>
  </div>

  <div class="profile-tab">
    <% if @user == current_user %>
    <nav>
      <div class="nav nav-tabs d-flex justify-content-center" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-posts-tab" data-toggle="tab" href="#nav-posts" role="tab" aria-controls="nav-posts" aria-selected="true">POSTS</a>
        <a class="nav-item nav-link" id="nav-saved-tab" data-toggle="tab" href="#nav-saved" role="tab" aria-controls="nav-saved" aria-selected="false">SAVED</a>
      </div>
    </nav>
    <% end %>
    <div class="tab-content pb-3" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-posts" role="tabpanel" aria-labelledby="nav-posts-tab">
        <div class="row">
          <%= render "post", {posts: @posts} %>
        </div>
      </div>
      <div class="tab-pane fade" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
        <div class="row">
          <%= render "post", {posts: @saved} if @user == current_user %>
        </div>
      </div>
    </div>
  </div>
</div>