config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :follows, only: [:index ,:create, :destroy], shallow: true
    resources :followeds, only: [:index ,:create, :destroy], shallow: true
    resources :rooms do
      resources :room_messages, only: [:index, :create, :destroy], shallow: true
      collection do
        get "download", as: "download"
      end
    end
  end

  resources :posts, only: [:index, :create, :show, :edit, :update,:destroy] do
    resources :photos, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end
end

app/views/shared/_devisemes.html.erb
<% if resource.errors.any? %>
 <script type="text/javascript">
   <% resource.errors.full_messages.each do |value| %>
     toastr.error('<%= value %>')
   <% end %>
 </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-auto">
        <a href="" class="nav-item nav-link" href="#">ABOUT US</a>
        <a href="" class="nav-item nav-link" href="#">SUPPORT</a>
        <a href="" class="nav-item nav-link" href="#">BLOG</a>
        <a href="" class="nav-item nav-link" href="#">PRESS</a>
        <a href="" class="nav-item nav-link" href="#">API</a>
        <a href="" class="nav-item nav-link" href="#">JOB</a>
        <a href="" class="nav-item nav-link" href="#">PRIVACY</a>
        <a href="" class="nav-item nav-link" href="#">TERMS</a>
        <a href="" class="nav-item nav-link" href="#">DIRECTORY</a>
        <a href="" class="nav-item nav-link" href="#">LANGUAGE</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "Icon", posts_path, class: "navbar-brand core-sprite hide-text" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_tag users_path, method: :get, class: "form-inline my-2 my-lg-0 ml-md-auto", id: "users-search",
        remote: true do %>
        <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2 text-center common-btn",
          placeholder: "Search", autocomplete: "off" %>
        <div id="users-result"></div>
      <% end %>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <%= link_to "Direct",user_rooms_path(current_user.id), method: :get,
          class: "nav-link core-sprite explore-icon hide-text" %>
        </li>
        <li class="nav-item">
          <a class="nav-link core-sprite notification-icon hide-text" href="#">Notification</a>
        </li>
        <li class="nav-item">
          <a class="nav-link core-sprite profile-icon hide-text" href="/users/<%=current_user.id%>">Profile</a>
        </li>
      </ul>
    </div>
  </div>
</nav>