config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :follows, only: [:index ,:create, :destroy], shallow: true
    resources :followeds, only: [:index ,:create, :destroy], shallow: true
    resources :rooms do
      resources :room_messages, only: [:index, :create, :destroy], shallow: true
      collection do
        get "download", as: "download"
      end
    end
  end

  resources :posts, only: [:index, :create, :show, :edit, :update,:destroy] do
    resources :photos, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/controllers/rooms_controller.rb
require 'tempfile'
require 'csv'
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @rooms = Room.all
    @user = User.find(params[:user_id])
  end

  def create
    @room = Room.create(params_room)
    if @room.save
      flash[:notice] = "Okay :)"
    else
      flash[:alert] = "Oh no !!"
    end
    redirect_to user_rooms_path(current_user)
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.room_messages
    @user = User.find(params[:user_id])
    respond_to :js
  end

  def edit
    @room = Room.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(params_room)
      flash[:notice] = "It's edited sucessfully"
    else
      flash[:alert] = "Oh Nooo !!!"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    if @room
      if @room.destroy
        flash[:notice] = "Okay :)"
      else
        flash[:alert] = "Oh no !!"
      end
    else
      flash[:alert] = "Conversation does not existed"
    end
    redirect_to user_rooms_path
  end

  def download
    @messages = RoomMessage.all
    test_file = Tempfile.new("TestFile.csv")
    header = ["Users", "Messages"]
    CSV.open(test_file, "wb", headers: header ) do |writer|
      @messages.each do |element|
        writer << [element.messages, element.user.name]
      end
    end
    test_file.rewind
    File.open(test_file.path, "r") do |f|
      send_data(f.read, filename: "TestFile.csv")
    end
    File.delete(test_file.path)
    test_file.close
    test_file.unlink
  end

  private
  def params_room
    params.permit(:name, :user_id)
  end
end

app/views/rooms/_message_form.html.erb
<%= form_tag user_room_room_messages_path(user, room), method: :post, remote: true, class: "md-form mt-3 text-right" do %>
  <%= text_field_tag :new_message, params[:new_message], placeholder: "Write something.. ", autocomplete: "off",
                     class: "form-control btn-sm border-0 text-right"%>
<% end %>

app/views/rooms/_room_edit_form.html.erb
<%= form_with url:user_room_path(user.id, room.id), method: :patch,
    remote: true, :class => "row" do |form| %>
  <%= form.text_field :name, placeholder: room.name, class: "form-control comment-input border-0 col-8" %>
<% end %>

app/views/rooms/_room_messages_list.html.erb
<% messages.each do |message| %>
  <% if message.user_id == current_user.id %>
    <div class="chat-message-container mt-3">
      <div class="row no-gutters justify-content-md-end">
        <div class="col col-lg-9">
          <div class="alert alert-dark text-left justify-content-center">
            <p class="mb-1">
              <%= message.messages %>
            </p>

            <div class="text-right">
              <small>
                <%= message.created_at %>
              </small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="chat-message-container mt-3">
      <div class="row no-gutters">
        <div class="col-auto">
          <%= image_tag user_avatar(message.user), class: "post-author-icon" %>
        </div>
        <div class="col-9">
          <div class="alert alert-info text-left justify-content-center">
            <p class="mb-1">
              <%= message.messages %>
            </p>

            <div class="text-right">
              <small>
                <%= message.created_at %>
              </small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% @rooms.each do |room| %>
  <div class="row p-2 border-bottom border-darker">
    <div id="room-<%= room.id %>">
      <%= link_to room.name, user_room_path(@user.id, room.id), method: :get, class: "btn border-0", remote: true %>
    </div>
    <div class="my-md-auto ml-auto" id="room-<%= room.id %>-edit-btn">
      <a class="core-sprite more-options hide-text ml-auto" data-toggle="collapse" href="#collapseExample<%= room.id %>" role="button" aria-expanded="false" aria-controls="collapseExample"></a>
      <div class="collapse" id="collapseExample<%= room.id %>">
        <%= link_to "Edit", edit_user_room_path(user.id, room.id), method: :get, remote: true, class: "btn common-btn border-darker"%>
        <%= link_to "Delete", user_room_path(user.id, room.id), method: :delete, remote: true, class: "btn common-btn border-darker"%>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/_user_conversation.html.erb
<% if users.present? %>
  <% users.each do |user| %>
    <%= link_to user_room_room_messages_path(user.id, room.id), method: :get, class: "no-text-decoration normal-color" do %>
      <div class="search-result-item text-sm-left"><%= user.name %></div>
    <% end %>
  <% end %>
<% else %>
  <div class="p-3">
    No results found
  </div>
<% end %>

app/views/rooms/edit.js.erb
$(`#room-<%= @room.id %>`).html('<%= j render "room_edit_form", {user: @user, room: @room} %>');
$(`#room-<%= @room.id %>-edit-btn`).html('<%= link_to "Save", user_rooms_path(@user) %>');

app/views/rooms/index.html.erb
<div class="room container m-4 p-3 border border-darker rounded ">
  <div class="row justify-content-md-center ml-1  border-bottom border-darker">
    <div class="create-room col-2 text-lg-start ">
      <div class="row create-conversation p-2">
        <%= form_tag user_rooms_path(@user.id), method: :post, remote: true do %>
          <%= hidden_field :user_id, value: @user.id %>
          <%= text_field_tag :name, params[:name], class: "form-inline border-0", placeholder: "Start a conversation" %>
        <% end %>
      </div>
    </div>
    <div class="col text-lg-center p-2 ">
      Direct
    </div>
    <div class="download-trial p-1 m-2">
      <%= link_to "Download", download_user_rooms_path(@user.id), class: "btn btn-sm btn-primary" %>
    </div>
  </div>
  <div class="row justify-content-md-start align-self-lg-center ml-1">
    <div class="all-rooms col-4 text-lg-start border-right border-darker">
      <%= render "rooms_list", {user: @user}%>
    </div>
    <div class="room-messages-box col-8 text-lg-center">
<!--      Choose user to message-->
      <div class="text-messages-box overflow-auto">
      </div>
      <div class="create-message-box">
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.js.erb
$('.text-messages-box').html('<%= j render "rooms/room_messages_list", {messages: @messages} %>');
$('.create-message-box').html('<%= j render "message_form", {user: @user, room: @room} %>')